BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Labels` (
	`ID`	INTEGER NOT NULL,
	`IID`	INTEGER NOT NULL,
	`LTID`	INTEGER NOT NULL,
	`Image`	TEXT NOT NULL,
	PRIMARY KEY(`ID`)
);
CREATE TABLE IF NOT EXISTS `LabelType` (
	`ID`	INTEGER NOT NULL,
	`Explanation`	TEXT NOT NULL,
	PRIMARY KEY(`ID`)
);
CREATE TABLE IF NOT EXISTS `Images` (
	`ID`	INTEGER NOT NULL,
	`Image`	TEXT NOT NULL,
	`IName`	TEXT NOT NULL,
	`IType`	INTEGER NOT NULL,
	`Width`	INTEGER NOT NULL,
	`Height`	INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);
COMMIT;
